version: '3'

services:
  web:
    build: ./docker/web
    ports:
    - 80:80
    volumes:
    - ./:/var/www/html
    depends_on:
    - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_ROOT_PASSWORD: root
      POSTGRES_DATABASE: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pw
    ports:
    - 5432:5432
    volumes:
    - postgres-db:/var/lib/postgres

  pgadmin4: 
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@localhost
      PGADMIN_DEFAULT_PASSWORD: adminpass
    ports: 
      - 8888:80
    depends_on: 
      - postgres


volumes:
  postgres-db:
